
import React, { useState, useEffect, useMemo } from 'react';
import { useAuth } from '../authContext';
import { StorageService } from '../services/storageService';
import { Guest } from '../types';
import { RSVP_STATUSES } from '../constants';
import { 
  Plus, 
  Search, 
  Loader2,
  Trash2,
  RefreshCw,
  FileText,
  X,
} from 'lucide-react';

export const Guests: React.FC = () => {
  const { user } = useAuth();
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('All');
  const [isLoading, setIsLoading] = useState(false);
  const [guestList, setGuestList] = useState<Guest[]>([]);
  const [isFetching, setIsFetching] = useState(true);

  const initialFormState = {
    name: '',
    phone: '',
    city: '',
    vipStatus: false,
    men: 0,
    women: 0,
    children: 0,
    relationship: 'Family',
    ownCar: 'No (Need Transport)',
    invitedBy: '',
    rsvpStatus: 'Pending' as Guest['rsvpStatus'],
    invitationSent: 'Not Sent',
    notes: '',
    group: 'Other' as Guest['group'],
    eventDate: new Date().toISOString().split('T')[0],
  };

  const [formData, setFormData] = useState(initialFormState);

  const refreshGuests = async () => {
    if (!user) return;
    setIsFetching(true);
    try {
      const data = await StorageService.getGuests(user.id, user.role);
      setGuestList(data);
    } catch (err) {
      console.error(err);
    } finally {
      setIsFetching(false);
    }
  };

  useEffect(() => {
    refreshGuests();
  }, [user]);

  const filteredGuests = useMemo(() => {
    return guestList.filter(g => {
      const name = g.name || "";
      const phone = g.phone || "";
      const matchesSearch = name.toLowerCase().includes(searchQuery.toLowerCase()) || 
                            phone.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesStatus = statusFilter === 'All' || g.rsvpStatus === statusFilter;
      return matchesSearch && matchesStatus;
    });
  }, [guestList, searchQuery, statusFilter]);

  const handleExportPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const rowsHtml = filteredGuests.map((g, i) => `
      <tr>
        <td>${i + 1}</td>
        <td><b>${g.name}</b>${g.vipStatus ? ' (VIP)' : ''}</td>
        <td>${g.city}</td>
        <td>${g.totalPersons} (M:${g.men} W:${g.women} C:${g.children})</td>
        <td>${g.rsvpStatus}</td>
        <td>${g.invitedBy}</td>
      </tr>
    `).join('');

    printWindow.document.write(`
      <html>
        <head>
          <title>Guest List - GuestNama</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #333; }
            .header { border-bottom: 2px solid #f59e0b; padding-bottom: 20px; margin-bottom: 30px; }
            h1 { margin: 0; color: #0f172a; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background: #f8fafc; text-align: left; padding: 12px; border: 1px solid #e2e8f0; font-size: 12px; text-transform: uppercase; }
            td { padding: 12px; border: 1px solid #e2e8f0; font-size: 13px; }
            .footer { margin-top: 40px; font-size: 10px; color: #94a3b8; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Guest List Report</h1>
            <p>Generated for: ${user?.name} | Total Guests: ${filteredGuests.length}</p>
          </div>
          <table>
            <thead>
              <tr><th>#</th><th>Name</th><th>City</th><th>Group Size</th><th>Status</th><th>Reference</th></tr>
            </thead>
            <tbody>${rowsHtml}</tbody>
          </table>
          <div class="footer">Generated by GuestNama Secure System - ${new Date().toLocaleString()}</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const handleAddGuest = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name.trim() || !user) return;

    setIsLoading(true);
    try {
      const newGuest: Guest = {
        ...formData,
        id: crypto.randomUUID(),
        userId: user.id,
        checkedIn: false,
        totalPersons: (Number(formData.men) || 0) + (Number(formData.women) || 0) + (Number(formData.children) || 0)
      };
      await StorageService.addGuest(newGuest);
      await refreshGuests();
      setIsFormOpen(false);
      setFormData(initialFormState);
    } catch (err) {
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Remove this guest permanently?")) return;
    try {
      await StorageService.deleteGuest(id);
      await refreshGuests();
    } catch (err) {
      console.error(err);
    }
  };

  const toggleRsvpStatus = async (guest: Guest) => {
    const currentIndex = RSVP_STATUSES.indexOf(guest.rsvpStatus as any);
    const nextIndex = (currentIndex + 1) % RSVP_STATUSES.length;
    const nextStatus = RSVP_STATUSES[nextIndex] as Guest['rsvpStatus'];
    setGuestList(prev => prev.map(g => g.id === guest.id ? { ...g, rsvpStatus: nextStatus } : g));
    try {
      await StorageService.updateGuestStatus(guest.id, nextStatus);
    } catch (err) {
      refreshGuests();
    }
  };

  return (
    <div className="space-y-6 lg:space-y-8 animate-in fade-in duration-500 pb-12">
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
        <div>
          <h1 className="text-2xl lg:text-3xl font-bold text-[#0f172a]">Guest Directory</h1>
          <p className="text-slate-500 mt-1 text-sm">Manage event access and RSVPs</p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <button onClick={handleExportPDF} className="flex-1 lg:flex-none p-3.5 bg-white border border-slate-200 rounded-2xl text-slate-500 hover:text-indigo-600 shadow-sm active:scale-90 transition-all cursor-pointer flex justify-center" title="Export to PDF">
            <FileText className="w-5 h-5" />
          </button>
          <button onClick={refreshGuests} className="flex-1 lg:flex-none p-3.5 bg-white border border-slate-200 rounded-2xl text-slate-500 hover:text-amber-500 shadow-sm active:scale-90 transition-all cursor-pointer flex justify-center" title="Sync Records">
            <RefreshCw className={`w-5 h-5 ${isFetching ? 'animate-spin text-amber-500' : ''}`} />
          </button>
          <button onClick={() => setIsFormOpen(true)} className="w-full lg:w-auto bg-amber-500 hover:bg-amber-600 text-white px-8 py-4 rounded-2xl font-bold transition-all shadow-lg active:scale-95 flex items-center justify-center gap-2 cursor-pointer">
            <Plus className="w-5 h-5" /> Add Guest
          </button>
        </div>
      </div>

      <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden flex flex-col">
        <div className="p-4 lg:p-6 border-b border-slate-100 bg-slate-50/30 flex flex-col lg:flex-row gap-4 items-center justify-between">
          <div className="relative w-full lg:max-w-md">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input 
              type="text"
              placeholder="Search guests..."
              className="w-full pl-11 pr-4 py-3.5 bg-white border border-slate-200 rounded-2xl focus:ring-2 focus:ring-amber-500 outline-none transition-all text-sm"
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
            />
          </div>
          <div className="flex items-center gap-2 overflow-x-auto w-full lg:w-auto pb-2 lg:pb-0 no-scrollbar">
            {['All', ...RSVP_STATUSES].map(status => (
              <button 
                key={status} 
                onClick={() => setStatusFilter(status)} 
                className={`px-5 py-2.5 rounded-xl text-xs font-bold whitespace-nowrap border transition-all cursor-pointer active:scale-90 ${statusFilter === status ? 'bg-[#0f172a] text-white border-[#0f172a]' : 'bg-white text-slate-500 border-slate-200 hover:border-amber-200'}`}
              >
                {status}
              </button>
            ))}
          </div>
        </div>

        <div className="overflow-x-auto no-scrollbar">
          <table className="w-full text-left min-w-[600px]">
            <thead>
              <tr className="bg-slate-50">
                <th className="px-6 py-4 text-[10px] font-black uppercase text-slate-400 tracking-widest">Name</th>
                <th className="px-6 py-4 text-[10px] font-black uppercase text-slate-400 tracking-widest">Details</th>
                <th className="px-6 py-4 text-[10px] font-black uppercase text-slate-400 tracking-widest">Attendance</th>
                <th className="px-6 py-4 text-[10px] font-black uppercase text-slate-400 tracking-widest">Reference</th>
                <th className="px-6 py-4 text-right"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {filteredGuests.length > 0 ? filteredGuests.map(guest => (
                <tr key={guest.id} className="hover:bg-slate-50/50 transition-colors group">
                  <td className="px-6 py-5">
                    <div className="flex items-center gap-3">
                      <div className={`w-9 h-9 rounded-xl flex items-center justify-center font-bold shadow-inner shrink-0 ${guest.vipStatus ? 'bg-amber-100 text-amber-600' : 'bg-slate-100 text-slate-400'}`}>
                        {guest.name.charAt(0)}
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm font-bold text-slate-800 truncate">{guest.name}</p>
                        <p className="text-[10px] text-slate-400 font-medium truncate">{guest.city}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-5 text-sm font-bold text-slate-600">
                    {guest.totalPersons} Pers.
                  </td>
                  <td className="px-6 py-5">
                    <button onClick={() => toggleRsvpStatus(guest)} className={`px-3 py-1.5 rounded-full text-[10px] font-black uppercase tracking-wider border transition-all cursor-pointer active:scale-90 ${guest.rsvpStatus === 'Confirmed' ? 'bg-emerald-50 text-emerald-600 border-emerald-100 hover:bg-emerald-100' : guest.rsvpStatus === 'Declined' ? 'bg-rose-50 text-rose-600 border-rose-100 hover:bg-rose-100' : 'bg-amber-50 text-amber-600 border-amber-100 hover:bg-amber-100'}`}>
                      {guest.rsvpStatus}
                    </button>
                  </td>
                  <td className="px-6 py-5 text-xs font-bold text-slate-500 uppercase tracking-tight truncate max-w-[120px]">{guest.invitedBy}</td>
                  <td className="px-6 py-5 text-right">
                    <button onClick={() => handleDelete(guest.id)} className="p-2 text-slate-200 hover:text-rose-500 hover:bg-rose-50 rounded-xl transition-all cursor-pointer active:scale-90">
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </td>
                </tr>
              )) : (
                <tr><td colSpan={5} className="py-20 text-center text-slate-400 italic font-medium">No guests matching filters found.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {isFormOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-[#0f172a]/40 backdrop-blur-md animate-in fade-in" onClick={() => setIsFormOpen(false)} />
          <div className="relative w-full max-w-lg bg-white rounded-[32px] p-6 lg:p-8 shadow-2xl animate-in zoom-in-95 duration-200 max-h-[90vh] overflow-y-auto custom-scrollbar">
            <div className="flex items-center justify-between mb-8">
              <h2 className="text-xl lg:text-2xl font-bold text-[#0f172a]">New Guest Entry</h2>
              <button onClick={() => setIsFormOpen(false)} className="p-2 hover:bg-slate-50 rounded-full transition-colors cursor-pointer active:scale-90"><X className="w-5 h-5" /></button>
            </div>
            <form onSubmit={handleAddGuest} className="space-y-5 lg:space-y-6">
              <div className="grid grid-cols-2 gap-4">
                <div className="col-span-2">
                  <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2 ml-1">Guest Name</label>
                  <input required className="w-full px-5 py-3.5 bg-slate-50 border border-slate-100 focus:border-amber-500 rounded-2xl outline-none" placeholder="e.g. Sameer Abbas" value={formData.name} onChange={e => setFormData(p => ({ ...p, name: e.target.value }))} />
                </div>
                <div>
                  <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2 ml-1">City</label>
                  <input required className="w-full px-5 py-3.5 bg-slate-50 border border-slate-100 focus:border-amber-500 rounded-2xl outline-none" placeholder="City" value={formData.city} onChange={e => setFormData(p => ({ ...p, city: e.target.value }))} />
                </div>
                <div>
                  <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2 ml-1">Reference</label>
                  <input required className="w-full px-5 py-3.5 bg-slate-50 border border-slate-100 focus:border-amber-500 rounded-2xl outline-none" placeholder="Invited By" value={formData.invitedBy} onChange={e => setFormData(p => ({ ...p, invitedBy: e.target.value }))} />
                </div>
                <div className="col-span-2 grid grid-cols-3 gap-3">
                  <div>
                    <label className="block text-[9px] font-black text-slate-500 uppercase tracking-widest mb-1.5 ml-1">Men</label>
                    <input type="number" min="0" className="w-full px-3 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none" value={formData.men} onChange={e => setFormData(p => ({ ...p, men: Number(e.target.value) }))} />
                  </div>
                  <div>
                    <label className="block text-[9px] font-black text-slate-500 uppercase tracking-widest mb-1.5 ml-1">Women</label>
                    <input type="number" min="0" className="w-full px-3 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none" value={formData.women} onChange={e => setFormData(p => ({ ...p, women: Number(e.target.value) }))} />
                  </div>
                  <div>
                    <label className="block text-[9px] font-black text-slate-500 uppercase tracking-widest mb-1.5 ml-1">Children</label>
                    <input type="number" min="0" className="w-full px-3 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none" value={formData.children} onChange={e => setFormData(p => ({ ...p, children: Number(e.target.value) }))} />
                  </div>
                </div>
              </div>
              <button disabled={isLoading} className="w-full py-4.5 bg-[#9333ea] hover:bg-[#7e22ce] text-white font-bold rounded-2xl shadow-xl transition-all active:scale-95 cursor-pointer flex items-center justify-center">
                {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : 'Register Guest'}
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
